apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: github-secret
spec:
  path: secret/ad/ad-accel-online-ml/lume-online-ml/gh-secrets
  type: kubernetes.io/dockerconfigjson
  keys:
    - username
    - password
  templates:
    ".dockerconfigjson": |
      {
          "auths": {
              "ghcr.io":{
                  "username":"{% .Secrets.username %}",
                  "password":"{% .Secrets.password %}",
                  "auth":"{% list .Secrets.username ":" .Secrets.password | join "" | b64enc %}"
              }
          }
      }